# Generated by Django 2.2.16 on 2022-11-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221125_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredient',
            options={},
        ),
    ]
