# Generated by Django 2.2.16 on 2022-11-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221126_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tima', to='recipes.Tag'),
        ),
    ]
