# Generated by Django 2.2.16 on 2022-11-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20221127_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredient',
            old_name='ingredient',
            new_name='ingredient_name',
        ),
        migrations.RenameField(
            model_name='amountingredient',
            old_name='recipe',
            new_name='recipe_name',
        ),
    ]
