# Generated by Django 2.2.16 on 2022-11-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20221127_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredient',
            old_name='ingredient',
            new_name='ingredient_name',
        ),
    ]
