# Generated by Django 2.2.16 on 2022-11-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20221127_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredient',
            old_name='ingredient_name',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='amountingredient',
            old_name='recipe_name',
            new_name='recipe',
        ),
    ]
