# Generated by Django 2.2.16 on 2022-11-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20221130_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipeamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientinrecipe', to='recipes.Recipe'),
        ),
    ]
