# Generated by Django 2.2.16 on 2022-12-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_auto_20221208_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hex_code',
            field=models.CharField(max_length=32, unique=True, verbose_name='Цвет'),
        ),
    ]
