# Generated by Django 2.2.16 on 2022-12-08 10:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_auto_20221208_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hex_code',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
