# Generated by Django 2.2.16 on 2022-11-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_follow'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
